import {
  Leaf,
  TrendingUp,
  ShieldAlert,
  Building2,
} from "lucide-react";

export default function ImpactAnalysis() {

  const impacts = [

    {
      title: "Economic Impact",
      value: "High",
      icon: <TrendingUp size={26}/>,
      color: "text-green-400",
    },

    {
      title: "Environmental",
      value: "Moderate",
      icon: <Leaf size={26}/>,
      color: "text-emerald-400",
    },

    {
      title: "Public Safety",
      value: "Low Risk",
      icon: <ShieldAlert size={26}/>,
      color: "text-orange-400",
    },

    {
      title: "Infrastructure",
      value: "Positive",
      icon: <Building2 size={26}/>,
      color: "text-cyan-400",
    },

  ];

  return (

    <div className="bg-slate-900 border border-slate-700 rounded-2xl p-6">

      <h2 className="text-2xl font-bold">

        AI Impact Analysis

      </h2>

      <p className="text-slate-400 mt-2 mb-6">

        Predicted impact generated by BharatVerse AI

      </p>

      <div className="grid grid-cols-2 gap-5">

        {impacts.map((item)=>(

          <div
            key={item.title}
            className="bg-slate-800 rounded-xl p-5 border border-slate-700"
          >

            <div className={item.color}>

              {item.icon}

            </div>

            <h3 className="mt-4 font-semibold">

              {item.title}

            </h3>

            <p className={`mt-2 text-xl font-bold ${item.color}`}>

              {item.value}

            </p>

          </div>

        ))}

      </div>

      <div className="mt-8">

        <h3 className="font-semibold mb-3">

          AI Confidence

        </h3>

        <div className="w-full h-3 rounded-full bg-slate-700">

          <div
            className="h-3 rounded-full bg-cyan-400"
            style={{width:"92%"}}
          />

        </div>

        <p className="mt-2 text-cyan-400">

          92% Confidence

        </p>

      </div>

    </div>

  );

}