import {
  Brain,
  Download,
  FileDown,
  CheckCircle2,
  XCircle,
  AlertTriangle,
} from "lucide-react";

export default function RecommendationPanel() {

  const recommendations = [

    {
      title: "Increase Disaster Preparedness",
      priority: "Critical",
      color: "bg-red-500/20 text-red-400",
    },

    {
      title: "Allocate Additional Healthcare Budget",
      priority: "High",
      color: "bg-orange-500/20 text-orange-400",
    },

    {
      title: "Expand Renewable Energy Programs",
      priority: "Medium",
      color: "bg-yellow-500/20 text-yellow-400",
    },

    {
      title: "Improve Rural Infrastructure",
      priority: "Medium",
      color: "bg-cyan-500/20 text-cyan-400",
    },

  ];

  return (

    <div className="bg-slate-900 border border-slate-700 rounded-2xl p-6">

      <div className="flex justify-between items-center mb-6">

        <div>

          <h2 className="text-2xl font-bold flex items-center gap-3">

            <Brain className="text-cyan-400"/>

            AI Recommendations

          </h2>

          <p className="text-slate-400 mt-2">

            Generated by BharatVerse Policy Intelligence Engine

          </p>

        </div>

        <button className="bg-cyan-500 hover:bg-cyan-600 px-5 py-3 rounded-xl flex items-center gap-2">

          <Download size={18}/>

          Export

        </button>

      </div>

      <div className="space-y-4">

        {recommendations.map((item)=>(

          <div
            key={item.title}
            className="bg-slate-800 border border-slate-700 rounded-xl p-5 flex justify-between items-center"
          >

            <div>

              <h3 className="font-semibold text-lg">

                {item.title}

              </h3>

              <span className={`${item.color} px-3 py-1 rounded-full text-sm mt-2 inline-block`}>

                {item.priority}

              </span>

            </div>

            <AlertTriangle className="text-yellow-400"/>

          </div>

        ))}

      </div>

      <div className="flex flex-wrap gap-4 mt-8">

        <button className="bg-green-600 hover:bg-green-700 px-6 py-3 rounded-xl flex items-center gap-2">

          <CheckCircle2 size={18}/>

          Approve

        </button>

        <button className="bg-red-600 hover:bg-red-700 px-6 py-3 rounded-xl flex items-center gap-2">

          <XCircle size={18}/>

          Reject

        </button>

        <button className="bg-slate-700 hover:bg-slate-600 px-6 py-3 rounded-xl flex items-center gap-2">

          <FileDown size={18}/>

          Download Report

        </button>

      </div>

    </div>

  );

}