import Navbar from "../components/Navbar";
import Sidebar from "../components/Sidebar";

import {
  Brain,
  ShieldAlert,
  TrafficCone,
  Zap,
  TrendingUp,
  CheckCircle2,
  Clock3,
} from "lucide-react";

export default function AIRecommendation() {

  const recommendations = [

    {
      title: "Flood Response",
      agent: "Climate AI",
      priority: "Critical",
      icon: <ShieldAlert size={28}/>,
      color: "border-red-500",
      badge: "bg-red-500/20 text-red-400",
      description:
        "Deploy emergency response teams to Chennai and nearby coastal districts."
    },

    {
      title: "Traffic Diversion",
      agent: "Traffic AI",
      priority: "High",
      icon: <TrafficCone size={28}/>,
      color: "border-orange-500",
      badge: "bg-orange-500/20 text-orange-400",
      description:
        "Redirect vehicles through Outer Ring Road to reduce congestion."
    },

    {
      title: "Energy Optimization",
      agent: "Energy AI",
      priority: "Medium",
      icon: <Zap size={28}/>,
      color: "border-yellow-500",
      badge: "bg-yellow-500/20 text-yellow-400",
      description:
        "Shift renewable energy to hospitals and emergency shelters."
    },

    {
      title: "Economic Support",
      agent: "Economy AI",
      priority: "Medium",
      icon: <TrendingUp size={28}/>,
      color: "border-green-500",
      badge: "bg-green-500/20 text-green-400",
      description:
        "Allocate emergency relief funds for affected MSMEs."
    }

  ];

  return (

    <div className="bg-slate-950 min-h-screen text-white">

      <Navbar/>

      <div className="flex">

        <Sidebar/>

        <main className="flex-1 p-8">

          <div className="flex justify-between items-center mb-8">

            <div>

              <h1 className="text-4xl font-bold flex items-center gap-3">

                <Brain className="text-cyan-400"/>

                AI Recommendation Engine

              </h1>

              <p className="text-slate-400 mt-2">

                Unified recommendations generated by all AI agents.

              </p>

            </div>

            <div className="bg-green-500/20 text-green-400 px-4 py-2 rounded-xl">

              ● AI Synced

            </div>

          </div>

          {/* Summary */}

          <div className="grid grid-cols-1 md:grid-cols-4 gap-6 mb-8">

            <SummaryCard title="Recommendations" value="18"/>
            <SummaryCard title="Critical" value="3"/>
            <SummaryCard title="Completed" value="11"/>
            <SummaryCard title="Pending" value="7"/>

          </div>

          {/* Recommendation Cards */}

          <div className="space-y-6">

            {recommendations.map((item)=>(

              <div
                key={item.title}
                className={`bg-slate-900 border ${item.color} rounded-2xl p-6`}
              >

                <div className="flex justify-between">

                  <div className="flex gap-5">

                    <div className="text-cyan-400">

                      {item.icon}

                    </div>

                    <div>

                      <h2 className="text-2xl font-bold">

                        {item.title}

                      </h2>

                      <p className="text-slate-400 mt-2">

                        {item.agent}

                      </p>

                    </div>

                  </div>

                  <span className={`${item.badge} px-4 py-2 rounded-xl h-fit`}>

                    {item.priority}

                  </span>

                </div>

                <p className="text-slate-300 mt-6 leading-7">

                  {item.description}

                </p>

                <div className="flex gap-4 mt-6">

                  <button className="bg-cyan-500 hover:bg-cyan-600 px-5 py-3 rounded-xl">

                    Approve

                  </button>

                  <button className="bg-slate-800 hover:bg-slate-700 px-5 py-3 rounded-xl">

                    View Details

                  </button>

                </div>

              </div>

            ))}

          </div>

          {/* Footer */}

          <div className="mt-8 bg-slate-900 rounded-2xl border border-slate-700 p-6">

            <div className="flex justify-between">

              <div className="flex items-center gap-3">

                <CheckCircle2 className="text-green-400"/>

                <span>

                  AI Decision Confidence

                </span>

              </div>

              <span className="text-green-400 font-bold">

                96.8%

              </span>

            </div>

            <div className="flex justify-between mt-5">

              <div className="flex items-center gap-3">

                <Clock3 className="text-cyan-400"/>

                <span>

                  Last Updated

                </span>

              </div>

              <span>

                2 minutes ago

              </span>

            </div>

          </div>

        </main>

      </div>

    </div>

  );

}

function SummaryCard({title,value}){

  return(

    <div className="bg-slate-900 border border-slate-700 rounded-2xl p-6">

      <p className="text-slate-400">

        {title}

      </p>

      <h2 className="text-3xl font-bold mt-3">

        {value}

      </h2>

    </div>

  )

}